### ISSUE TITLE
Store arbitrary data in imgur?

### ISSUE THREAD

**Issue by elimisteve** [wayspurrchen/beamp#1]
That's what I'm looking to do! Storing arbitrary data in PNGs is apparently possible with [s2png](https://github.com/dbohdan/s2png), but with s2png and beamp I'm worried that compression done by imgur will corrupt the data I've stored in said images.

Any idea if this is a problem? It may not be for PNGs, since, according to [this page](http://users.wfu.edu/matthews/misc/graphics/formats/formats.html), "[t]he compression is exactly reversible, so the image is recovered exactly." Thanks!

**Comment by elimisteve** [comment]
Which image-hosting services have you tried hosting images from beamp at?

**Comment by wayspurrchen** [comment]
Hi! For compression-free images that you plan to use later, I would not recommend imgur, Facebook, or any other public image service that tries to offer images for others to view. These services almost always apply their own compression, especially with large image formats like BMP, and I imagine they use some sophisticated compression to crunch down JPG as well.

If your goal is storage for later further modification, I would rely on something like Google Drive that merely stores files as they are. If you're trying to embed data into PNGs on imgur, and imgur says that the image is perfectly recoverable, then you should be OK. Otherwise, if you're trying to make images with embedded data publicly consumable, you might need to roll your own solution with AWS S3 or something similar.

I haven't personally tried hosting beamp images that are for being un-BMPed, so I couldn't tell you if it would work or not. Let me know if you find anything out though!
